### ISSUE TITLE
Update IdentityModel dependency

### ISSUE THREAD

**Issue by yilativ** [clawrenceks/ReferenceTokenExchange#12]
We are using IdentityModel4, when attempting to use this for the api gateway, the IdentityModel3 dependency is conflicting and creating the following error: 

> System.TypeLoadException: Could not load type 'IdentityModel.Client.DiscoveryResponse' from assembly 'IdentityModel, Version=4.3.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f'.
   at Clawrenceks.ReferenceTokenExchange.Services.TokenExchangeService.ExchangeTokenAsync(String referenceToken, ReferenceTokenExchangeOptions options)
   at Clawrenceks.ReferenceTokenExchange.Configuration.ReferenceTokenExchangeMiddleware.Invoke(HttpContext context, IReferenceTokenExchangeServiceFactory tokenExchangeServiceFactory)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

Would it be possible to Update with the latest IdentityModel?

**Comment by clawrenceks** [comment]
@yilativ Would you be able to provide a sample project reproducing this behaviour please? I have this component in use in projects that are using Identity Model 4 and I do not see this issue.
